[package]
name = "geomag"
version = "0.1.3"
license = "Apache-2.0"
edition = "2021"

[dependencies]
libm = { version = "0.2", optional = true }

[features]
default = ["igrf", "wmm"]
igrf = []
wmm = []