[package]
name = "geomag"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
libm = { version = "0.2", optional = true }

[features]
default = ["igrf", "wmm"]
igrf = []
wmm = []