[package]
name = "geomag"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = [] }
num-traits = "0.2"

[features]
default = ["igrf", "wmm"]
chrono = []
igrf = []
wmm = []