[package]
name = "geomag-jni"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
geomag = { path = "../geomag", features = ["chrono"] }
jni = "0.21.1"

[lib]
name = "geomag_jni"
crate_type = ["cdylib"]